/**
 * Mercado Pago client & helpers
 *
 * Docs: https://github.com/mercadopago/sdk-nodejs
 *
 * Env vars required:
 *   MP_ACCESS_TOKEN  – server-side secret key
 *   MP_PUBLIC_KEY    – client-side key (sent to the mobile app)
 *   MP_WEBHOOK_SECRET – used to verify incoming webhook signatures
 */

import { MercadoPagoConfig, Customer, CustomerCard, Payment, Preference } from 'mercadopago';
import { createHmac, timingSafeEqual } from 'crypto';
import { logger } from './logger';

// ── Client ────────────────────────────────────────────────────────────────────

function getAccessToken(): string {
  const token = process.env.MP_ACCESS_TOKEN;
  if (!token) {
    logger.error('[MercadoPago] MP_ACCESS_TOKEN is not set');
    throw new Error('MP_ACCESS_TOKEN is not configured');
  }
  return token;
}

export function getMPClient(): MercadoPagoConfig {
  return new MercadoPagoConfig({
    accessToken: getAccessToken(),
    options: { timeout: 5000 },
  });
}

// ── Customers ─────────────────────────────────────────────────────────────────

/**
 * Finds or creates a Mercado Pago Customer for the given email.
 * Returns the MP customer ID.
 */
export async function findOrCreateCustomer(email: string): Promise<string> {
  const client = getMPClient();
  const customerApi = new Customer(client);

  // Search for existing customer by email
  const searchResult = await customerApi.search({ options: { email } });
  const results = searchResult.results ?? [];

  if (results.length > 0 && results[0].id) {
    logger.info(`[MercadoPago] Found existing customer for ${email}: ${results[0].id}`);
    return results[0].id;
  }

  // Create new customer
  const newCustomer = await customerApi.create({ body: { email } });
  if (!newCustomer.id) {
    throw new Error('Failed to create Mercado Pago customer – no id returned');
  }

  logger.info(`[MercadoPago] Created new customer for ${email}: ${newCustomer.id}`);
  return newCustomer.id;
}

// ── Cards ─────────────────────────────────────────────────────────────────────

/**
 * Saves a tokenised card to a MP customer.
 * The `cardToken` must be generated by the MP SDK on the client (mobile app)
 * using the user's raw card data – never sent to this server.
 */
export async function saveCardToCustomer(mpCustomerId: string, cardToken: string) {
  const client = getMPClient();
  const cardApi = new CustomerCard(client);

  const card = await cardApi.create({
    customerId: mpCustomerId,
    body: { token: cardToken },
  });

  logger.info(`[MercadoPago] Card saved for customer ${mpCustomerId}: ${card.id}`);
  return card;
}

/**
 * Lists all saved cards for a MP customer.
 */
export async function listCustomerCards(mpCustomerId: string) {
  const client = getMPClient();
  const cardApi = new CustomerCard(client);

  const result = await cardApi.list({ customerId: mpCustomerId });
  return result ?? [];
}

/**
 * Deletes a saved card from a MP customer.
 */
export async function deleteCustomerCard(mpCustomerId: string, cardId: string) {
  const client = getMPClient();
  const cardApi = new CustomerCard(client);

  await cardApi.remove({ customerId: mpCustomerId, cardId });
  logger.info(`[MercadoPago] Card ${cardId} deleted for customer ${mpCustomerId}`);
}

// ── Checkout Pro (web payments) ───────────────────────────────────────────────

export interface MPPreferenceInput {
  orderId: string;         // Used as external_reference to find the order on return
  description: string;     // e.g. "2x Entrada General – Lollapalooza 2026"
  amount: number;          // Total in CLP (integer)
  email: string;           // Payer email
  appUrl: string;          // e.g. https://sorykpass.com (no trailing slash)
  returnPath?: string;     // e.g. "/api/mercadopago/return" (default)
}

/**
 * Creates a MercadoPago Checkout Pro preference and returns the init_point URL.
 * The user is redirected to this URL to complete payment.
 * On return, MP sends GET to back_urls with: external_reference, payment_id, status.
 */
export async function createPreference(input: MPPreferenceInput): Promise<string> {
  const client = getMPClient();
  const preferenceApi = new Preference(client);

  const returnPath = input.returnPath ?? '/api/mercadopago/return';
  const returnUrl = `${input.appUrl}${returnPath}`;

  const response = await preferenceApi.create({
    body: {
      items: [
        {
          id: input.orderId,
          title: input.description,
          quantity: 1,
          unit_price: input.amount,
          currency_id: 'CLP',
        },
      ],
      payer: { email: input.email },
      external_reference: input.orderId,
      back_urls: {
        success: returnUrl,
        failure: returnUrl,
        pending: returnUrl,
      },
      auto_return: 'approved',
    },
  });

  if (!response.init_point) {
    throw new Error('MercadoPago did not return an init_point URL');
  }

  logger.info(`[MercadoPago] Preference created: id=${response.id} for order ${input.orderId}`);
  return response.init_point;
}

// ── Payments ──────────────────────────────────────────────────────────────────

export interface MPPaymentInput {
  amount: number;
  currency: string;
  cardToken: string;       // One-time token created by mobile app from saved card + CVV
  installments: number;
  paymentMethodId: string; // e.g. "visa", "master"
  mpCustomerId: string;
  email: string;
  description: string;
  externalReference: string; // our orderNumber
}

/**
 * Creates a card payment on Mercado Pago.
 * Returns the full MP payment object.
 */
export async function createMPPayment(input: MPPaymentInput) {
  const client = getMPClient();
  const paymentApi = new Payment(client);

  const response = await paymentApi.create({
    body: {
      transaction_amount: input.amount,
      token: input.cardToken,
      installments: input.installments,
      payment_method_id: input.paymentMethodId,
      description: input.description,
      external_reference: input.externalReference,
      capture: true,
      payer: {
        email: input.email,
        id: input.mpCustomerId,
      },
    },
  });

  logger.info(`[MercadoPago] Payment created: id=${response.id} status=${response.status}`);
  return response;
}

// ── Webhook verification ──────────────────────────────────────────────────────

/**
 * Verifies the x-signature header sent by Mercado Pago on webhook calls.
 * MP sends: x-signature: ts=<timestamp>,v1=<hmac>
 *
 * Docs: https://www.mercadopago.com.ar/developers/es/docs/your-integrations/notifications/webhooks
 */
export function verifyMPWebhookSignature(
  xSignature: string,
  xRequestId: string,
  dataId: string, // query param ?data.id=xxx
): boolean {
  const secret = process.env.MP_WEBHOOK_SECRET;
  if (!secret) {
    logger.warn('[MercadoPago] MP_WEBHOOK_SECRET not set – skipping signature verification');
    return true; // fail-open in dev; set the secret in production
  }

  try {
    const parts = Object.fromEntries(
      xSignature.split(',').map((p) => p.split('=') as [string, string])
    );
    const ts = parts['ts'];
    const v1 = parts['v1'];

    if (!ts || !v1) return false;

    // MP manifest string: id:<dataId>;request-id:<xRequestId>;ts:<ts>;
    const manifest = `id:${dataId};request-id:${xRequestId};ts:${ts};`;

    const expected = createHmac('sha256', secret)
      .update(manifest)
      .digest('hex');

    return timingSafeEqual(Buffer.from(expected), Buffer.from(v1));
  } catch (err) {
    logger.error('[MercadoPago] Signature verification error', err instanceof Error ? err : undefined);
    return false;
  }
}

/**
 * Fetches a single payment from MP by id (used in webhook handler).
 */
export async function getMPPaymentById(mpPaymentId: string | number) {
  const client = getMPClient();
  const paymentApi = new Payment(client);
  return paymentApi.get({ id: Number(mpPaymentId) });
}
