/**
 * POST /api/mercadopago/customers
 *
 * Finds or creates a Mercado Pago Customer for the authenticated user and
 * attaches a tokenised card to it.
 *
 * Body (JSON):
 *   { cardToken: string }
 *
 * The `cardToken` is a one-time token generated by the Mercado Pago mobile SDK
 * using the user's raw card data on the device – the raw PAN never reaches
 * this server.
 *
 * Returns:
 *   { mpCustomerId, card: { id, lastFourDigits, expirationMonth, expirationYear, paymentMethodId } }
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { createFreshCustomer, findOrCreateCustomer, saveCardToCustomer } from '@/lib/mercadopago';
import { RateLimitPresets } from '@/lib/rate-limiter';
import { logger } from '@/lib/logger';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
      'Access-Control-Max-Age': '86400',
    },
  });
}

const bodySchema = z.object({
  cardToken: z.string().min(1, 'Se requiere el token de tarjeta'),
});

export async function POST(request: NextRequest) {
  try {
    const ip =
      request.headers.get('x-forwarded-for') ??
      request.headers.get('x-real-ip') ??
      'unknown';
    const rateCheck = await RateLimitPresets.api.isAllowed(`card-save:${ip}`);
    if (!rateCheck.allowed) {
      return NextResponse.json(
        { error: 'Demasiadas solicitudes. Intenta en un momento.' },
        { status: 429 },
      );
    }

    const user = await requireAuth();
    const body = await request.json();

    const validation = bodySchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: 'Datos inválidos', details: validation.error.issues },
        { status: 400 },
      );
    }

    const { cardToken } = validation.data;

    // 1. Get or create the MP customer
    let mpCustomerId = user.mpCustomerId ?? null;

    if (!mpCustomerId) {
      // Always create a FRESH customer when DB has no mpCustomerId.
      // Using findOrCreate would re-find the old (potentially broken) MP customer
      // by email and cause "customer server error" on payment.
      mpCustomerId = await createFreshCustomer(user.email);
      // Persist the customer ID so we don't create duplicates
      await prisma.user.update({
        where: { id: user.id },
        data: { mpCustomerId },
      });
    }

    // 2. Save the card to the MP customer
    // If the stored mpCustomerId is stale (customer deleted / different env),
    // MP returns a 404/not-found error — we catch it, create a fresh customer, and retry once.
    let card;
    try {
      card = await saveCardToCustomer(mpCustomerId, cardToken);
    } catch (cardErr) {
      const errObj = cardErr as Record<string, unknown>;
      const cause = Array.isArray(errObj?.cause) ? errObj.cause as { code?: number | string }[] : [];
      const isNotFound =
        errObj?.status === 404 ||
        cause.some((c) => c.code === 2002 || c.code === '2002') ||
        (typeof errObj?.message === 'string' && errObj.message.toLowerCase().includes('not found'));

      if (isNotFound) {
        logger.warn(`[customers] Stale mpCustomerId ${mpCustomerId}, creating fresh customer`);
        mpCustomerId = await createFreshCustomer(user.email);
        await prisma.user.update({ where: { id: user.id }, data: { mpCustomerId } });
        card = await saveCardToCustomer(mpCustomerId, cardToken);
      } else {
        throw cardErr;
      }
    }

    return NextResponse.json({
      mpCustomerId,
      card: {
        id: card.id,
        lastFourDigits: card.last_four_digits,
        expirationMonth: card.expiration_month,
        expirationYear: card.expiration_year,
        paymentMethodId: card.payment_method?.id,
        paymentMethodName: card.payment_method?.name,
        issuerName: card.issuer?.name,
        cardholderName: card.cardholder?.name,
      },
    });
  } catch (error) {
    logger.error('[POST /api/mercadopago/customers]', error instanceof Error ? error : undefined);
    return NextResponse.json(
      {
        error: 'Error al guardar la tarjeta',
        details: error instanceof Error ? error.message : 'Error desconocido',
      },
      { status: 500 },
    );
  }
}
