-- AlterTable
ALTER TABLE "event_seats" ADD COLUMN IF NOT EXISTS "x" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "y" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "sections" ADD COLUMN IF NOT EXISTS "height" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "rotation" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "width" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "x" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "y" DOUBLE PRECISION;
UPDATE "sections" SET "rotation" = 0 WHERE "rotation" IS NULL;
